title: Meu Site Jekyll
description: >- # Descrição do seu site
  Este é um site de exemplo criado com Jekyll e hospedado no GitHub Pages.
baseurl: "/seu-repositorio" # O nome do seu repositório
url: "https://seu-usuario.github.io" # A URL do seu GitHub Pages
